---
# File: tasks/CentOS.yml - CentOS tasks for Vault

- name: "Distribution specific variables"
  include_vars: main.yml

- name: OS packages
  yum: "name={{ item }} state=present"
  with_items: "{{ vault_centos_os_packages }}"
  tags: installation

- name: Download Vault
  get_url: "url={{ vault_zip_url }} dest=/tmp/{{ vault_centos_pkg }} sha256sum={{ vault_centos_sha256 }} timeout=74"
  tags: installation

- name: Install Vault
  unarchive: "copy=no creates=/usr/local/bin/vault src=/tmp/{{ vault_centos_pkg }} dest=/usr/local/bin/ owner={{ vault_user }} group={{ vault_group }} mode=0755"
  tags: installation

- name: Cleanup
  file: path=/tmp/"{{ vault_centos_pkg }}" state=absent
  tags: installation
