---
# File: tasks/Debian.yml - Debian tasks for Vault

- name: "Distribution specific variables"
  include_vars: main.yml

- name: OS packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: "{{ vault_debian_os_packages }}"
  tags: installation

- name: Download Vault
  get_url: "url={{ vault_zip_url }} dest=/tmp/{{ vault_debian_pkg }} sha256sum={{ vault_debian_sha256 }} timeout=74 validate_certs=False"
  tags: installation

- name: Install Vault
  unarchive: "copy=no creates=/usr/local/bin/vault src=/tmp/{{ vault_debian_pkg }} dest=/usr/local/bin/ owner={{ vault_user }} group={{ vault_group }} mode=0755"
  tags: installation

- name: Cleanup
  file: path=/tmp/"{{ vault_debian_pkg }}" state=absent
  tags: installation
