---
# File: tasks/install_enterprise.yml
#       Vault Enterprise package installation tasks

- name: "[Enterprise] Install OS packages"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vault_os_packages }}"
  tags: installation

- name: "[Enterprise] Check for {{ role_path }}/files/{{ vault_enterprise_shasums }}"
  local_action: stat path="{{ role_path }}/files/{{ vault_enterprise_shasums }}"
  become: no
  run_once: true
  register: vault_checksum

- fail:
    msg: "[Enterprise] FATAL - no Vault Enterprise SHASUMs file found. Please add the zip file to this role's files directory."
  when: not vault_checksum.stat.exists | bool

- name: "[Enterprise] Get checksum from {{ role_path }}/files/{{ vault_enterprise_shasums }}"
  local_action: shell grep "{{ vault_enterprise_pkg }}" "{{ role_path }}/files/{{ vault_enterprise_shasums }}" | awk '{print $1}'
  become: no
  run_once: true
  register: vault_sha256
  tags: installation

- name: "[Enterprise] Check for {{ role_path }}/files/{{ vault_enterprise_pkg }}"
  local_action: stat path="{{ role_path }}/files/{{ vault_enterprise_pkg }}"
  become: no
  run_once: true
  register: vault_package

- fail:
    msg: "[Enterprise] FATAL - no Vault Enterprise binary package file found. Please add the zip file to this role's files directory."
  when: not vault_package.stat.exists | bool

- name: "[Enterprise] Unzip {{ role_path }}/files/{{ vault_enterprise_pkg }}"
  local_action: unarchive src="{{ role_path }}/files/{{ vault_enterprise_pkg }}" dest="{{ role_path }}/files/" creates="{{ role_path }}/files/vault"
  become: no
  run_once: true
  tags: installation

- name: "[Enterprise] Install Vault Enterprise v{{ vault_enterprise_version }} from {{ role_path }}/files/vault"
  copy:
    src: "{{ role_path }}/files/vault"
    dest: "{{ vault_bin_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"
  tags: installation

- name: "[Enterprise] Remove {{ role_path }}/files/vault"
  local_action: file path="{{ item }}" state="absent"
  become: no
  with_fileglob: "{{ role_path }}/files/vault"
  run_once: true
  tags: installation
