---
# File: tasks/install.yml - package installation tasks for vault

- name: OS packages
  package: "name={{ item }} state=present"
  with_items: "{{ vault_os_packages }}"
  tags: installation

- name: Get vault package checksum file
  become: no
  connection: local
  get_url: "url={{ vault_checksum_file_url }} dest={{ role_path }}/files/vault_{{ vault_version }}_SHA256SUMS"
  run_once: true
  tags: installation

- name: Get vault package checksum
  become: no
  connection: local
  shell: "grep {{ vault_pkg }} {{ role_path }}/files/vault_{{ vault_version }}_SHA256SUMS"
  run_once: true
  register: vault_sha256
  tags: installation

- name: Download vault
  become: no
  connection: local
  get_url: "url={{ vault_zip_url }} dest={{ role_path }}/files/{{ vault_pkg }} checksum=sha256:{{ vault_sha256.stdout.split(' ')|first }} timeout=42"
  run_once: true
  tags: installation

- name: Unarchive vault
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ vault_pkg }} dest={{ role_epath }}/files/ creates={{ role_path }}/files/vault"
  run_once: true
  tags: installation

- name: Install vault
  copy: "src={{ role_path }}/files/vault dest=/usr/local/bin/ owner={{ vault_user }} group={{ vault_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/vault* state=absent"
  run_once: true
  tags: installation
